### ISSUE TITLE
省去安装后的数据插件迁移步骤/原版与miao版云崽共存

### ISSUE THREAD

**Issue by WindraiteLesd** [TimeRainStarSky/Yunzai#1]
能否在config中添加data、plugin和logs文件夹路径的配置项，以此省去通过在其他目录部署的方式从原版更换到miao版云崽/TRSS-Yunzai中需要的数据文件迁移步骤和实现灵活切换云崽版本

**Comment by TimeRainStarSky** [comment]
这个从bot里实现比较麻烦，不如在文件系统层实现，比如软链接`ln -s`或挂载`mount --bind`
