### ISSUE TITLE
群聊中使用 `兑换码` 指令报错

### ISSUE THREAD

**Issue by gxy12345** [TimeRainStarSky/Yunzai#10]
使用ComWeChat，私聊可以正常分条发送，群聊中报错，错误信息如下
<img width="702" alt="image" src="https://user-images.githubusercontent.com/13727139/233884672-bfdcaa74-3cd4-44c5-b8ca-bf4173c0c045.png">

**Comment by TimeRainStarSky** [comment]
已修复 557517c
