### ISSUE TITLE
Bot is not defined

### ISSUE THREAD

**Issue by Frodo20** [TimeRainStarSky/Yunzai#101]
<img width="558" alt="截屏2024-05-21 10 38 32" src="https://github.com/TimeRainStarSky/Yunzai/assets/65547857/1d37ac7c-baef-4d8b-85b4-3e02a8e0fccb">
启动过程中报错如图

**Comment by TimeRainStarSky** [comment]
```sh
rd /s /q node_modules
pnpm i
```
