### ISSUE TITLE
合并信息

### ISSUE THREAD

**Issue by PeelSign** [TimeRainStarSky/Yunzai#11]
请问什么时候删除发送合并消息，会额外发送一条[CQ:,=好友转发消息]![IMG_20230424_183733.jpg](https://user-images.githubusercontent.com/99504275/233972748-e9f6a1f1-56f2-4fd2-a733-96ac3c14a88f.jpg)

**Comment by TimeRainStarSky** [comment]
插件逻辑问题暂不考虑更改

**Comment by TimeRainStarSky** [comment]
你可以自己修改配置文件忽略
```yaml
# 是否忽略无效的CQ码, 如果为假将原样发送
ignore-invalid-cqcode: false
```

**Comment by PeelSign** [comment]
好的，感谢解答
