### ISSUE TITLE
miao-plugin 在切屏 (快捷键 alt+tab）时会有一个不存在的，看不见的窗口，名为 miao-plugin

### ISSUE THREAD

**Issue by liucheng12156** [TimeRainStarSky/Yunzai#113]
如题，具体使用为trss云崽，添加插件 miao-plugin，liangshi-calc，guoba-plugin，panel-plugin，qqbot-plugin 和 trss-plugin，经过测试这个窗口在任务管理器中无法定位，发送#喵喵帮助后出现（发送前未出现）
![image](https://github.com/user-attachments/assets/b077ad55-d627-401c-9517-707d73389202)

**Comment by TimeRainStarSky** [comment]
把puppeteer和Chrome更新到最新版本后再试
```
pnpm up puppeteer@latest
```

**Comment by liucheng12156** [comment]
以上已更新，无效果

**Comment by lniuua** [comment]
同样出现了这种情况

**Comment by TimeRainStarSky** [comment]
> 同样出现了这种情况

降级chromium到127以下

**Comment by MWTJC** [comment]
[https://github.com/yoimiya-kokomi/Miao-Yunzai/issues/476](url)
