### ISSUE TITLE
云崽更新出现报错

### ISSUE THREAD

**Issue by qingtian-crazy** [TimeRainStarSky/Yunzai#114]
服务器：windows server 2019数据中心版
触发报错的原因；QQ聊天框以主人发送  #更新
报错情况：
![d1baf0d99f195426572caa01cddfee43](https://github.com/user-attachments/assets/198a8517-7a6e-4b28-a501-055873090161)
![1](https://github.com/user-attachments/assets/c797d86b-e661-4ecf-8677-c269829ef2a8)
![f361aea615e9e90dd9786c8d945e2b6f](https://github.com/user-attachments/assets/823a2bde-b4c4-482c-ba84-d15cb732ac7b)

尝试的方法：尚未使用#强制更新，因为之前碰到过类似情况强制更新结果yunzai打不开了，重新覆盖了一遍库才正常运行

**Comment by TimeRainStarSky** [comment]
上面都写了，执行那两条或者强制更新
