### ISSUE TITLE
QQBot发送消息错误

### ISSUE THREAD

**Issue by KawaYiLab** [TimeRainStarSky/Yunzai#115]
@机器人发送#更新面板 消息会重复发一次
![image](https://github.com/user-attachments/assets/f1c7f21e-bdaa-4477-b579-17c2b411fa06)
报错如图，如何解决（频道内是正常的）
![image](https://github.com/user-attachments/assets/0c17cd7f-08b3-4e49-9209-d4a61f72c37b)

**Comment by VenenoSix24** [comment]
老哥，怎么解决的，我也是这样了，捣鼓好久没解决
