### ISSUE TITLE
使用Shamrock接入时出现请求超时

### ISSUE THREAD

**Issue by Zhuazizizi** [TimeRainStarSky/Yunzai#116]
连接上后过一小会出现超时 断开连接然后再连接，会一直重复这样，在没有收到消息也会一直重复这个情况
在连着时功能似乎正常，但因为时不时断一下经常会发不出消息。
在家真机Shamrock和云服务器yunazi
![image](https://github.com/user-attachments/assets/fd5790d5-b41f-49ec-90a2-1da83908942d)

**Comment by TimeRainStarSky** [comment]
服务器建议使用 LLOneBot/NapCat/Lagrange
