### ISSUE TITLE
昨天更新之后Bot转发组合消息报错

### ISSUE THREAD

**Issue by beiyuan324** [TimeRainStarSky/Yunzai#119]
![75ee6268727f0d0e18bc2b488a73d574](https://github.com/user-attachments/assets/d0e5e577-d6cd-4e7b-bea1-610f5c01b4a0)

**Comment by beiyuan324** [comment]
已解决，重启NTQQ即可，但不知道原因。

**Comment by TimeRainStarSky** [comment]
截图不完整，关键报错没截到
