### ISSUE TITLE
更新了LLOneBot v3.28.6之后报错

### ISSUE THREAD

**Issue by beiyuan324** [TimeRainStarSky/Yunzai#124]
![image](https://github.com/user-attachments/assets/45ffc6b0-e196-4099-8873-a898172591ef)

**Comment by beiyuan324** [comment]
是否更新了api导致的

**Comment by beiyuan324** [comment]
突然发现是所有的api都不行了，尝试重新装一下LLOB

**Comment by beiyuan324** [comment]
还原到LLOB v3.26.6版本正常，确认是LLOB更新导致的。

**Comment by coder9029** [comment]
+1，我这也报错了，我下的[v3.29.4](https://github.com/LLOneBot/LLOneBot/releases/tag/v3.29.4)

**Comment by TimeRainStarSky** [comment]
LLOneBot问题找LLOneBot作者
