### ISSUE TITLE
客户端未实现get_csrf_token导致频繁断连

### ISSUE THREAD

**Issue by eya46** [TimeRainStarSky/Yunzai#126]
如图
用的napcat-docer
![image](https://github.com/user-attachments/assets/6bb6f5b2-d2e5-40a9-b771-69b2fd1d6c80)

希望能优化
![QQ_1724162498562](https://github.com/user-attachments/assets/7597c3cf-66b6-4793-857d-3722c2d8f2b0)

**Comment by TimeRainStarSky** [comment]
未实现应返回错误未实现，而不是不返回
