### ISSUE TITLE
频道bot抽卡记录转义问题

### ISSUE THREAD

**Issue by MilvusSky** [TimeRainStarSky/Yunzai#130]
url = url.replace(/&amp;/g, '&')

dealUrl函数需要添加上述代码以处理频道bot消息中"&"被转义成"&amp;"的问题。(我记得之前PR过来着，怎么没了QAQ)

**Comment by TimeRainStarSky** [comment]
&就是&，你在发什么无意义的东西

**Comment by MilvusSky** [comment]
见截图，我写的没问题，是显示自动转义了。频道bot也有这个问题。抽卡链接带&传过去就是amp了
![0b416c01-077b-4fa7-856d-8fbed6042f81](https://github.com/user-attachments/assets/98b2357e-5f8f-4611-8fb0-fc9f890390b6)
![9b54d90f-bc97-4789-9e07-771707f574d0](https://github.com/user-attachments/assets/13e7cb87-d890-4bb7-87e9-748659c2d127)

**Comment by MilvusSky** [comment]
> &就是&，你在发什么无意义的东西

见截图，我写的没问题，是显示自动转义了。频道bot也有这个问题。抽卡链接带&传过去就是amp了
![0b416c01-077b-4fa7-856d-8fbed6042f81](https://github.com/user-attachments/assets/98b2357e-5f8f-4611-8fb0-fc9f890390b6)
![9b54d90f-bc97-4789-9e07-771707f574d0](https://github.com/user-attachments/assets/13e7cb87-d890-4bb7-87e9-748659c2d127)

**Comment by MilvusSky** [comment]
> > &就是&，你在发什么无意义的东西
> 
> 见截图，我写的没问题，是显示自动转义了。频道bot也有这个问题。抽卡链接带&传过去就是amp了 ![0b416c01-077b-4fa7-856d-8fbed6042f81](https://private-user-images.githubusercontent.com/85536598/368513328-98b2357e-5f8f-4611-8fb0-fc9f890390b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTI5MjIsIm5iZiI6MTcyNjY1MjYyMiwicGF0aCI6Ii84NTUzNjU5OC8zNjg1MTMzMjgtOThiMjM1N2UtNWY4Zi00NjExLThmYjAtZmM5Zjg5MDM5MGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA5NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MzA1YjYwOTk1OTM0ODk4NmJiNjg0MThkOGYwMmE5MTg4MmRjMjI4Mzk3NDRjMGNhM2ZhN2RmYWQ1NWUyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cUdhy5fhSxTMb6laOI2rmiBkld2gG29DWEFo1sbnEaE) ![9b54d90f-bc97-4789-9e07-771707f574d0](https://private-user-images.githubusercontent.com/85536598/368513353-13e7cb87-d890-4bb7-87e9-748659c2d127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTI5MjIsIm5iZiI6MTcyNjY1MjYyMiwicGF0aCI6Ii84NTUzNjU5OC8zNjg1MTMzNTMtMTNlN2NiODctZDg5MC00YmI3LTg3ZTktNzQ4NjU5YzJkMTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA5NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMGZjMzQ2NzU4OGYzYWE3NmIwZjQ0ZTk3NTZiOTcyN2NmM2JhOTQ5MzQzYzJmZTk4ZjBiOTkxNThiZWU2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2BBob6WeygTnACs2K4nh5xTimPhGQ_cKFpEEqw3zPlQ)

消息传到后台带被转义成amp的&，因此bot就会返回链接有误

**Comment by TimeRainStarSky** [comment]
https://github.com/zhinjs/qq-official-bot/issues/new
