### ISSUE TITLE
启动后发送会渲染图片的指令会出现白框，关闭命令行后也会跟着消失

### ISSUE THREAD

**Issue by lniuua** [TimeRainStarSky/Yunzai#133]
![2](https://github.com/user-attachments/assets/9721b631-56fc-4835-8fc9-06a9a5bfb21a)

**Comment by TimeRainStarSky** [comment]
降级chromium到127以下

**Comment by MWTJC** [comment]
[https://github.com/yoimiya-kokomi/Miao-Yunzai/issues/476](url)
