### ISSUE TITLE
启动时反复因connect ECONNREFUSED 127.0.0.1:6379重启

### ISSUE THREAD

**Issue by Jerry-c9** [TimeRainStarSky/Yunzai#137]
电脑小白，还望各位大佬指教🙏
![389a3c621cb6b49d6463118c102856bf](https://github.com/user-attachments/assets/1dfb18ad-3c15-4c00-a426-05750d699209)

**Comment by TimeRainStarSky** [comment]
右键管理员运行

**Comment by Jerry-c9** [comment]
我是用mys2安装的，用管理员身份运行仍然出现该问题，还望您帮忙再看看

（以及出现了这个东西是什么意思）
![image](https://github.com/user-attachments/assets/c69f9234-aad1-482c-9f0f-83909f7e9c0c)

**Comment by TimeRainStarSky** [comment]
自己检查安全软件，防火墙等设置

**Comment by Jerry-c9** [comment]
防火墙没开，火绒已添加信任区。

**Comment by TimeRainStarSky** [comment]
改用WSL

**Comment by Jerry-c9** [comment]
好的，我试试

**Comment by Jerry-c9** [comment]
我换一个电脑就没这个问题，不知道为什么。

**Comment by TimeRainStarSky** [comment]
> 我换一个电脑就没这个问题，不知道为什么。

反正你这电脑系统有问题，具体什么问题我也不知道
