### ISSUE TITLE
公告推送失败

### ISSUE THREAD

**Issue by PeelSign** [TimeRainStarSky/Yunzai#14]
![image](https://user-images.githubusercontent.com/99504275/234755868-64865806-9bc2-4222-b211-63173cad3387.png)

**Comment by PeelSign** [comment]
![image](https://user-images.githubusercontent.com/99504275/234756349-e120c001-1840-479f-8b07-197e148defd0.png)

**Comment by TimeRainStarSky** [comment]
已修复 af7284a
