### ISSUE TITLE
[BUG反馈] 添加表情功能发送失败

### ISSUE THREAD

**Issue by A1Panda** [TimeRainStarSky/Yunzai#140]
在#添加[表情名] 输入图片 或者视频作为表情输出时会报错
![image](https://github.com/user-attachments/assets/38dff393-4171-465e-84be-778935bd26e1)

**Comment by A1Panda** [comment]
用的napcat协议端

**Comment by A1Panda** [comment]
检查过是文件不存在
![image](https://github.com/user-attachments/assets/90b5bdfa-d03d-4c5d-a357-c97f3bebb8ad)

**Comment by A1Panda** [comment]
![image](https://github.com/user-attachments/assets/27d6b952-c32a-443d-8e32-cd78d06decee)

**Comment by TimeRainStarSky** [comment]
协议问题无法解决
