### ISSUE TITLE
BUG禁用私聊后，发送私聊消息会回复到群里

### ISSUE THREAD

**Issue by lniuua** [TimeRainStarSky/Yunzai#141]

**Comment by TimeRainStarSky** [comment]
日志

**Comment by lniuua** [comment]
![image](https://github.com/user-attachments/assets/2141c7c3-9b2d-4b80-9ac0-9303f4176398)

**Comment by TimeRainStarSky** [comment]
禁用临时会话

**Comment by 127Wzc** [comment]
我这边也有反馈这个问题了  排查发现临时对话这俩方法都存在 导致顺序优先匹配到了group里
![image](https://github.com/user-attachments/assets/6fae3060-05c2-41b7-9ded-651d883b6332)
