### ISSUE TITLE
docker方式安装后使用"tsyz"启动时报错

### ISSUE THREAD

**Issue by imlhhya** [TimeRainStarSky/Yunzai#142]
使用官方docker脚本安装完毕并提示使用"tsyz"启动机器人后，我输入命令启动机器人，在安装依赖时报错并结束了运行，试过了好几次也没能解决。附报错全过程
![Screenshot_2024_1215_181313](https://github.com/user-attachments/assets/40acb6a4-3b2b-4db3-93fe-bab5476191a2)
![Screenshot_2024_1215_181407](https://github.com/user-attachments/assets/54a18785-7118-4d43-8ba3-008219f30dff)

**Comment by TimeRainStarSky** [comment]
arm docker不在适配范围内
