### ISSUE TITLE
一Bot共用

### ISSUE THREAD

**Issue by AIxPha** [TimeRainStarSky/Yunzai#2]
是否可以把服务本地回环改成公网
让手机用户可以直接下载gocq连接
不用搭建直接使用

**Comment by TimeRainStarSky** [comment]
本来就是可以的

**Comment by AIxPha** [comment]
> 本来就是可以的

那如何把localhost改成公网IP呢

**Comment by TimeRainStarSky** [comment]
> > 本来就是可以的
> 
> 那如何把localhost改成公网IP呢

自己改go-cqhttp连接地址啊

**Comment by AIxPha** [comment]
> > > 本来就是可以的
> > 
> > 那如何把localhost改成公网IP呢
> 
> 自己改go-cqhttp连接地址啊

universal: ws://112.74.57.142:2536/go-cqhttp


配置文件改成这样服务器开放了2536端口


连接到反向WebSocket Universal服务器 ws://112.74.57.142:2536/go-cqhttp 时出现 错误: read tcp 172.19.0.1:46034->112.74.57.142:2536: read: connection reset by peer

**Comment by TimeRainStarSky** [comment]
> > > > 本来就是可以的
> > > 
> > > 
> > > 那如何把localhost改成公网IP呢
> > 
> > 
> > 自己改go-cqhttp连接地址啊
> 
> universal: ws://112.74.57.142:2536/go-cqhttp
> 
> 配置文件改成这样服务器开放了2536端口
> 
> 连接到反向WebSocket Universal服务器 ws://112.74.57.142:2536/go-cqhttp 时出现 错误: read tcp 172.19.0.1:46034->112.74.57.142:2536: read: connection reset by peer

扫了一下你这个IP，只开了22端口

**Comment by AIxPha** [comment]
> > > > > 本来就是可以的
> > > > 
> > > > 
> > > > 那如何把localhost改成公网IP呢
> > > 
> > > 
> > > 自己改go-cqhttp连接地址啊
> > 
> > universal: ws://112.74.57.142:2536/go-cqhttp
> > 
> > 配置文件改成这样服务器开放了2536端口
> > 
> > 连接到反向WebSocket Universal服务器 ws://112.74.57.142:2536/go-cqhttp 时出现 错误: read tcp 172.19.0.1:46034->112.74.57.142:2536: read: connection reset by peer
> 
> 扫了一下你这个IP，只开了22端口
好的
阿里云轻量，端口都开了，也独立开了2536

我换一台服务器试试

打扰了，感谢

**Comment by AIxPha** [comment]
> > > > > 本来就是可以的
> > > > 
> > > > 
> > > > 那如何把localhost改成公网IP呢
> > > 
> > > 
> > > 自己改go-cqhttp连接地址啊
> > 
> > 
> > 通用：ws://112.74.57.142:2536/go-cqhttp
> > 配置文件改成这样服务器开放了2536端口
> > 连接到反向WebSocket Universal服务器 ws://112.74.57.142:2536/go-cqhttp 时出现 错误： 读取 TCP 172.19.0.1：46034->112.74.57.142：2536：读取：对等方重置连接
> 
> 扫了一下你这个IP，只开了22端口




上午使用了阿里云和腾讯云都是轻量
使用Debian 11且用TRSS脚本部署TRSS云崽
端口全开不过后来发现ws://localhost:2536/go-cqhttp
在服务器本机上也无法连接gocq
刚才换成了Windows系统就可以了
公网也可以正常远程连接

应该是我个人问题
但还是讲一下
