### ISSUE TITLE
频道发送图片消息错误

### ISSUE THREAD

**Issue by Lycofuture** [TimeRainStarSky/Yunzai#21]
![Screenshot_20230511-162335_Termux](https://github.com/TimeRainStarSky/Yunzai/assets/77215384/e18f3173-4ce3-4e57-833c-8b632282b523)
在帮助后出现上面的错误，相关依赖以及版本都是update过的

**Comment by TimeRainStarSky** [comment]
更新并重装浏览器

**Comment by Lycofuture** [comment]
> 更新并重装浏览器

都是最新的，启动不了了
![Screenshot_20230512-130418_Termux](https://github.com/TimeRainStarSky/Yunzai/assets/77215384/989e0db0-9edb-40c0-aa32-f00eb2bef73c)

**Comment by Lycofuture** [comment]
独立genshin，但是没有完全独立，还是需要genshin才能运行，不然启动不了

**Comment by TimeRainStarSky** [comment]
> 独立genshin，但是没有完全独立，还是需要genshin才能运行，不然启动不了

独立的是仓库，我有说过独立是没有也能运行了？

**Comment by TimeRainStarSky** [comment]
> > 更新并重装浏览器
> 
> 都是最新的，启动不了了
> ![Screenshot_20230512-130418_Termux](https://github.com/TimeRainStarSky/Yunzai/assets/77215384/989e0db0-9edb-40c0-aa32-f00eb2bef73c)
> 

用脚本装试试
