### ISSUE TITLE
puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by mmmjie** [TimeRainStarSky/Yunzai#22]
![image](https://github.com/TimeRainStarSky/Yunzai/assets/45615222/3c6a3948-982c-4375-9fda-5616224feb20)

都最新的了，按依旧报错
![image](https://github.com/TimeRainStarSky/Yunzai/assets/45615222/f9e125d1-eb07-4505-97d2-c568d7e84511)

环境是ubuntu22.04 genshi 和miaoplus 也最新了

**Comment by TimeRainStarSky** [comment]
有很多方法修复，自己查，我建议用脚本 https://trss.me
