### ISSUE TITLE
ComWeChat发不出图片

### ISSUE THREAD

**Issue by 3186418613** [TimeRainStarSky/Yunzai#25]
使用xiaoyao-cvs-plugin时微信发送#扫码登录后，只发送了免责声明没发二维码

![截图](https://github.com/TimeRainStarSky/Yunzai/assets/77595393/68410f7f-45f7-4079-bf64-c564609e8ca7)

yunzai日志:
`[TRSSYz][09:21:34.553][INFO] [wxid_678v6gfxvjdo22] 好友消息：[wxid_b4lao4d6oxa322] #扫码登录
[TRSSYz][09:21:34.570][INFO] [wxid_678v6gfxvjdo22] 发送好友消息：[wxid_b4lao4d6oxa322] 免责声明:您将通过扫码完成获取米游社sk以及ck。
本Bot将不会保存您的登录状态。
我方仅提供米游社查询及相关游戏内容服务,若您的账号封禁、被盗等处罚与我方无关。
害怕风险请勿扫码~
[TRSSYz][09:21:34.779][MARK] puppeteer Chromium 启动中...
chromium ws://127.0.0.1:50387/devtools/browser/9c561fd0-baf1-483e-bd1e-d005c8dd2695
[TRSSYz][09:21:35.089][MARK] puppeteer Chromium 启动成功
[TRSSYz][09:21:36.259][MARK] [图片生成][xiaoyao-cvs-plugin/qrCode/index][0次] 67.76kb 1147ms
[TRSSYz][09:21:36.261][INFO] [wxid_678v6gfxvjdo22] 发送好友消息：[wxid_b4lao4d6oxa322] [{"type":"at","qq":"wxid_b4lao4d6oxa322"},"\n请扫码以完成绑定\n",{"type":"image","file":"base64://..."}]
Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.`

ComWeChat日志:
`05-21 09:21:34 [SUCCESS] wechatbot_client | WeChat Manager | 生成事件[PrivateMessageEvent]:{'id': '56c4d721-3252-425a-82bb-1e8a57ebffbf', 'time': 1684632092.0, 'type': 'message', 'detail_type': 'private', 'sub_type': '', 'self': {'platform': 'wechat', 'user_id': 'wxid_678v6gfxvjdo22'}, 'message_id': '3826555963857732019', 'message': [MessageSegment(type='text', data={'text': '#扫码登录'})], 'alt_message': '#扫码登录', 'user_id': 'wxid_b4lao4d6oxa322'}
05-21 09:21:34 [SUCCESS] wechatbot_client | OneBot V12 | 收到action请求: {'action': 'send_message', 'params': {'detail_type': 'private', 'user_id': 'wxid_b4lao4d6oxa322', 'message': [{'type': 'text', 'data': {'text': '免责声明:您将通过扫码完成获取米游社sk以及ck。\n本Bot将不会保存您的登录状态。\n我方仅提供米游社查询...
05-21 09:21:36 [SUCCESS] wechatbot_client | OneBot V12 | 收到action请求: {'action': 'upload_file', 'params': {'type': 'data', 'data': 'iVBORw0KGgoAAAANSUhEUgAAAtAAAALsCAYAAADK74BKAAAAAXNSR0IArs4c6QAAIABJREFUeJzs3W9sXdWZ+PvHPo7/5Ti2bCduCK6Thk6OnQYldtBUYENUpES3qNyoSkQvJ+HPUD...
05-21 09:21:36 [SUCCESS] wechatbot_client | OneBot V12 | 收到action请求: {'action': 'send_message', 'params': {'detail_type': 'private', 'user_id': 'wxid_b4lao4d6oxa322', 'message': [{'type': 'mention', 'data': {'user_id': 'wxid_b4lao4d6oxa322'}}, {'type': 'text', 'data': ...`

**Comment by TimeRainStarSky** [comment]
ComWeChat问题，私聊无法发送提及会直接吞消息，给ComWeChat提issue
