### ISSUE TITLE
更新后云崽寄了，ERROR MOUDLE NOT FOUND

### ISSUE THREAD

**Issue by strike94** [TimeRainStarSky/Yunzai#27]
![image](https://github.com/TimeRainStarSky/Yunzai/assets/34638547/42b00813-dd57-48a9-9cf6-12aec66c5387)
更新后出现当前错误，重建配置文件也不行

**Comment by TimeRainStarSky** [comment]
`git clone --depth 1 https://gitee.com/TimeRainStarSky/Yunzai-genshin plugins/genshin`
