### ISSUE TITLE
更新后无法使用

### ISSUE THREAD

**Issue by CuteLittleSky** [TimeRainStarSky/Yunzai#35]
node app
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'oicq' imported from D:\SKYCRAFT\Yunzai\lib\plugins\loader.js
[90m    at new NodeError (node:internal/errors:399:5)[39m
[90m    at packageResolve (node:internal/modules/esm/resolve:783:9)[39m
[90m    at moduleResolve (node:internal/modules/esm/resolve:832:20)[39m
[90m    at defaultResolve (node:internal/modules/esm/resolve:1069:11)[39m
[90m    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:305:12)[39m
[90m    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:156:32)[39m
[90m    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)[39m
[90m    at link (node:internal/modules/esm/module_job:75:36)[39m {
  code: [32m'ERR_MODULE_NOT_FOUND'[39m
}

Node.js v20.2.0

**Comment by TimeRainStarSky** [comment]
```
pnpm i
```
