### ISSUE TITLE
go-cqhttp端是否支持自动同意好友及邀请加入群聊

### ISSUE THREAD

**Issue by 1034148617** [TimeRainStarSky/Yunzai#37]
在配置文件/config/other.yaml里设置autoFriend为1 但是QQ端（go-cqhttp）加好友没有反应，请问是否支持该功能；同时使用锅巴面板配置时，相关项报错`.for is not iterable`

**Comment by TimeRainStarSky** [comment]
1.暂不支持加好友功能
2.锅巴插件问题，找插件作者适配

**Comment by TimeRainStarSky** [comment]
已支持
