### ISSUE TITLE
使用WeChat Plugin报错

### ISSUE THREAD

**Issue by 3186418613** [TimeRainStarSky/Yunzai#42]
用WeChat Plugin时机器人发一条消息报错一次然后图还能正常发出去
![image](https://github.com/TimeRainStarSky/Yunzai/assets/77595393/ee827006-97a2-479f-9dd4-1d896e399aec)

**Comment by TimeRainStarSky** [comment]
已修复

**Comment by ITManCHINA** [comment]
> 已修复

此插件在图片渲染设置为200，或者使用`#角色`命令输出全部角色的时候无法发送图片，提示`Tips：上传媒体文件失败`，猜测是文件体积过大（？）导致的嘛，Miao-Yunzai在图片渲染为200的时候可正常发送图片

**Comment by TimeRainStarSky** [comment]
> > 已修复
> 
> 此插件在图片渲染设置为200，或者使用`#角色`命令输出全部角色的时候无法发送图片，提示`Tips：上传媒体文件失败`，猜测是文件体积过大（？）导致的嘛，Miao-Yunzai在图片渲染为200的时候可正常发送图片

是的

**Comment by ITManCHINA** [comment]
> > > 已修复
> > 
> > 
> > 此插件在图片渲染设置为200，或者使用`#角色`命令输出全部角色的时候无法发送图片，提示`Tips：上传媒体文件失败`，猜测是文件体积过大（？）导致的嘛，Miao-Yunzai在图片渲染为200的时候可正常发送图片
> 
> 是的

请问这个问题可以修复嘛，还是说其实这是个特性😮

**Comment by TimeRainStarSky** [comment]
> > > > 已修复
> > > 
> > > 
> > > 此插件在图片渲染设置为200，或者使用`#角色`命令输出全部角色的时候无法发送图片，提示`Tips：上传媒体文件失败`，猜测是文件体积过大（？）导致的嘛，Miao-Yunzai在图片渲染为200的时候可正常发送图片
> > 
> > 
> > 是的
> 
> 请问这个问题可以修复嘛，还是说其实这是个特性open_mouth

问上游 wechat4u
