### ISSUE TITLE
绑定国际服Hoyolab cookie时报错

### ISSUE THREAD

**Issue by TheTychoStar** [TimeRainStarSky/Yunzai#44]
提示错误：`绑定cookie失败：登录失效，请重新登录`

cookie都是刚登录Hoyolab后马上获取的，已尝试过：
- 在正常模式下退出登录后重新登录
- 无痕浏览模式下登录

均无法绑定，但国服可以成功绑定。

获取到的cookie格式如下，似乎是升级到了“**v2**”？
`cookie_token_v2=v2_CAQSDGMxxxxxxxxxxxxxxxxxxE_jM=; account_mid_v2=10xxxxxxxx_hy; account_id_v2=1xxxxxxx8; ltoken_v2=v2_CAISDGMxxxxxxxxxxxxxxxxxxE_jM=; ltmid_v2=10xxxxxxxx_hy; ltuid_v2=1xxxxxxx8`

**Comment by TimeRainStarSky** [comment]
找上游 Miao-Yunzai 反馈
