### ISSUE TITLE
meme.js插件无法使用

### ISSUE THREAD

**Issue by canyi2** [TimeRainStarSky/Yunzai#45]
![image](https://github.com/TimeRainStarSky/Yunzai/assets/95406510/f8711838-48ea-49a8-a5e5-436473cb8714)
![image](https://github.com/TimeRainStarSky/Yunzai/assets/95406510/6f197d17-b6c6-40b4-8cd2-744c700e3aaf)

**Comment by TimeRainStarSky** [comment]
找插件作者去
