### ISSUE TITLE
更新fcd674a后输入任何指令都报错

### ISSUE THREAD

**Issue by TheTychoStar** [TimeRainStarSky/Yunzai#49]
回滚到0b2e683就没问题了。
错误日志如下（是Discord bot）：

> [TRSSYz][13:01:39.053][ERRO] TypeError: Cannot read properties of null (reading 'makeForwardMsg')
>     at PluginsLoader.dealEvent (file:///home/ec2-user/trss/lib/plugins/loader.js:349:14)
>     at PluginsLoader.deal (file:///home/ec2-user/trss/lib/plugins/loader.js:173:10)
>     at messageEvent.execute (file:///home/ec2-user/trss/lib/events/message.js:12:18)
>     at Yunzai.<anonymous> (file:///home/ec2-user/trss/lib/listener/loader.js:30:73)
>     at Yunzai.emit (node:events:513:28)
>     at DiscordAdapter.makeMessage (file:///home/ec2-user/trss/plugins/Discord-Plugin/index.js:317:9)
>     at Client.<anonymous> (file:///home/ec2-user/trss/plugins/Discord-Plugin/index.js:386:12)
>     at Client.emit (node:events:513:28)
>     at Shard.emit (/home/ec2-user/trss/node_modules/.pnpm/eris@0.17.2/node_modules/eris/lib/gateway/Shard.js:247:26)
>     at Shard.wsEvent (/home/ec2-user/trss/node_modules/.pnpm/eris@0.17.2/node_modules/eris/lib/gateway/Shard.js:869:26)

**Comment by TimeRainStarSky** [comment]
已修复

**Comment by TheTychoStar** [comment]
更新到5e86f18后，还是报错。
错误日志和之前一样：

> [TRSSYz][04:20:04.846][ERRO] TypeError: Cannot read properties of null (reading 'makeForwardMsg')
>     at PluginsLoader.dealEvent (file:///home/ec2-user/trss/lib/plugins/loader.js:349:14)
>     at PluginsLoader.deal (file:///home/ec2-user/trss/lib/plugins/loader.js:173:10)
>     at messageEvent.execute (file:///home/ec2-user/trss/lib/events/message.js:12:18)
>     at Yunzai.<anonymous> (file:///home/ec2-user/trss/lib/listener/loader.js:30:73)
>     at Yunzai.emit (node:events:513:28)
>     at DiscordAdapter.makeMessage (file:///home/ec2-user/trss/plugins/Discord-Plugin/index.js:317:9)
>     at Client.<anonymous> (file:///home/ec2-user/trss/plugins/Discord-Plugin/index.js:386:12)
>     at Client.emit (node:events:513:28)
>     at Shard.emit (/home/ec2-user/trss/node_modules/.pnpm/eris@0.17.2/node_modules/eris/lib/gateway/Shard.js:247:26)
>     at Shard.wsEvent (/home/ec2-user/trss/node_modules/.pnpm/eris@0.17.2/node_modules/eris/lib/gateway/Shard.js:869:26)
>
