### ISSUE TITLE
comwechat这边拍一拍显示undefined

### ISSUE THREAD

**Issue by ayakasuki** [TimeRainStarSky/Yunzai#51]
comwechat这边拍一拍机器人显示undefined，无论是喵喵自带的戳一戳还是chuoyichuo.js都显示undefined 
![image](https://github.com/TimeRainStarSky/Yunzai/assets/20859971/96870b54-707c-4ad8-a185-92f59939eb92)

**Comment by TimeRainStarSky** [comment]
已修复
