### ISSUE TITLE
星铁的功能无法正常使用

### ISSUE THREAD

**Issue by Kochisa** [TimeRainStarSky/Yunzai#55]
[TRSSYz][17:05:18.821][INFO] [ko_1612564964] 群消息：[米家APP(ko_1272241577463953), 
ғᴜᴛᴜʀᴇ ʜᴏᴜsᴇ(ko_302459117)] *兑换码                                       
[TRSSYz][17:05:18.827][MARK] [喵喵:角色面板][profileChange][米家APP(ғᴜᴛᴜʀᴇ ʜ 
ᴜsᴇ)] #星铁兑换码                                                                 
[TRSSYz][17:05:27.930][INFO] [ko_1612564964] 群消息：[米家APP(ko_1272241577463953), 
ғᴜᴛᴜʀᴇ ʜᴏᴜsᴇ(ko_302459117)] *符玄攻略                                     
[TRSSYz][17:05:27.932][MARK] [米游社攻略][strategy][米家APP(ғᴜᴛᴜʀᴇ ʜᴏᴜsᴇ)]
 #星铁符玄攻略 

kook和QQ都是这个情况，命令发出去了，也识别到了，但是没有反馈。

**Comment by TimeRainStarSky** [comment]
找插件作者
