### ISSUE TITLE
设置主人后台看不到验证码

### ISSUE THREAD

**Issue by jiexi22** [TimeRainStarSky/Yunzai#57]
#设置主人 指令
在云崽后台和go-cq后台都看不到验证码

**Comment by 1103859909** [comment]
哥们 有解决办法吗

**Comment by A-Kevin1217** [comment]
至今不解决，也不给个其他方案？

**Comment by AIxPha** [comment]
> 至今没有解决，也没有给出其他方案？

本身就没有问题
不需要解决
而且没有提供相关日志

**Comment by A-Kevin1217** [comment]
> > 至今没有解决，也没有给出其他方案？
> 
> 本身就没有问题 不需要解决 而且没有提供相关日志

他就是在cq后台和yunzai后台都没有验证码
![71e1587ea95d41e95a4db5248e7868ee](https://github.com/TimeRainStarSky/Yunzai/assets/21151999/d8847cce-e38c-421e-8e71-858a5982d81e)
![3060f7d0868ea1b96080ac04c76d332b](https://github.com/TimeRainStarSky/Yunzai/assets/21151999/33b46cfc-c7ff-4fb4-a316-bee5c58d01f7)

**Comment by AIxPha** [comment]
> > > 至今没有解决，也没有给出其他方案？
> > 
> > 
> > 本身就没有问题 不需要解决 而且没有提供相关日志
> 
> 他就是在cq后台和yunzai后台都没有验证码 ![71e1587ea95d41e95a4db5248e7868ee](https://private-user-images.githubusercontent.com/21151999/297018218-d8847cce-e38c-421e-8e71-858a5982d81e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDIxNzMsIm5iZiI6MTcwNTQwMTg3MywicGF0aCI6Ii8yMTE1MTk5OS8yOTcwMTgyMTgtZDg4NDdjY2UtZTM4Yy00MjFlLThlNzEtODU4YTU5ODJkODFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEwNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmN2FiNDJmNmIwODRiODBiYmEwODI2YmI0OGZmZDIwYzc2M2NhMGU4MWJkOTVhNDMzMmRkN2Q0NjQzYjhjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._lukQ3CzNVkTnr81SemkjnqC3ul-IKzyHMu3WkGWjrw) ![3060f7d0868ea1b96080ac04c76d332b](https://private-user-images.githubusercontent.com/21151999/297018243-33b46cfc-c7ff-4fb4-a316-bee5c58d01f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDIxNzMsIm5iZiI6MTcwNTQwMTg3MywicGF0aCI6Ii8yMTE1MTk5OS8yOTcwMTgyNDMtMzNiNDZjZmMtYzdmZi00ZmI0LWEzMTYtYmVlNWM1OGQwMWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEwNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyM2Q2YzNkNGZlNGNiZDJmOWE1ZDBkYmE5MTMyZjE4YTVjZDAzYWVkYzIxYWI2NmIzYzFjYzMzZWFmYmVjMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4GzvGEawC3GNY51Un_wb51LAxTHjcSol0Fw2malbClY)

验证码在Yunzai的日志里
不会在gocq的日志

至于你的这个问题
你的gocq连接的不是你的后端
验证码当然不会在你的后端出现
这是你的问题
和项目没有关系

**Comment by A-Kevin1217** [comment]
> > > > 至今没有解决，也没有给出其他方案？
> > > 
> > > 
> > > 本身就没有问题 不需要解决 而且没有提供相关日志
> > 
> > 
> > 他就是在cq后台和yunzai后台都没有验证码 ![71e1587ea95d41e95a4db5248e7868ee](https://private-user-images.githubusercontent.com/21151999/297018218-d8847cce-e38c-421e-8e71-858a5982d81e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDIxNzMsIm5iZiI6MTcwNTQwMTg3MywicGF0aCI6Ii8yMTE1MTk5OS8yOTcwMTgyMTgtZDg4NDdjY2UtZTM4Yy00MjFlLThlNzEtODU4YTU5ODJkODFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEwNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmN2FiNDJmNmIwODRiODBiYmEwODI2YmI0OGZmZDIwYzc2M2NhMGU4MWJkOTVhNDMzMmRkN2Q0NjQzYjhjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._lukQ3CzNVkTnr81SemkjnqC3ul-IKzyHMu3WkGWjrw) ![3060f7d0868ea1b96080ac04c76d332b](https://private-user-images.githubusercontent.com/21151999/297018243-33b46cfc-c7ff-4fb4-a316-bee5c58d01f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDIxNzMsIm5iZiI6MTcwNTQwMTg3MywicGF0aCI6Ii8yMTE1MTk5OS8yOTcwMTgyNDMtMzNiNDZjZmMtYzdmZi00ZmI0LWEzMTYtYmVlNWM1OGQwMWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEwNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyM2Q2YzNkNGZlNGNiZDJmOWE1ZDBkYmE5MTMyZjE4YTVjZDAzYWVkYzIxYWI2NmIzYzFjYzMzZWFmYmVjMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4GzvGEawC3GNY51Un_wb51LAxTHjcSol0Fw2malbClY)
> 
> 验证码在Yunzai的日志里 不会在gocq的日志
> 
> 至于你的这个问题 你的gocq连接的不是你的后端 验证码当然不会在你的后端出现 这是你的问题 和项目没有关系

怎么就不是我的后端了。。。端口都是我自己设置的

**Comment by AIxPha** [comment]
> > > > > 至今没有解决，也没有给出其他方案？
> > > > 
> > > > 
> > > > 本身就没有问题 不需要解决 而且没有提供相关日志
> > > 
> > > 
> > > 他就是在cq后台和yunzai后台都没有验证码 ![71e1587ea95d41e95a4db5248e7868ee](https://private-user-images.githubusercontent.com/21151999/297018218-d8847cce-e38c-421e-8e71-858a5982d81e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDIxNzMsIm5iZiI6MTcwNTQwMTg3MywicGF0aCI6Ii8yMTE1MTk5OS8yOTcwMTgyMTgtZDg4NDdjY2UtZTM4Yy00MjFlLThlNzEtODU4YTU5ODJkODFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEwNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmN2FiNDJmNmIwODRiODBiYmEwODI2YmI0OGZmZDIwYzc2M2NhMGU4MWJkOTVhNDMzMmRkN2Q0NjQzYjhjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._lukQ3CzNVkTnr81SemkjnqC3ul-IKzyHMu3WkGWjrw) ![3060f7d0868ea1b96080ac04c76d332b](https://private-user-images.githubusercontent.com/21151999/297018243-33b46cfc-c7ff-4fb4-a316-bee5c58d01f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDIxNzMsIm5iZiI6MTcwNTQwMTg3MywicGF0aCI6Ii8yMTE1MTk5OS8yOTcwMTgyNDMtMzNiNDZjZmMtYzdmZi00ZmI0LWEzMTYtYmVlNWM1OGQwMWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEwNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyM2Q2YzNkNGZlNGNiZDJmOWE1ZDBkYmE5MTMyZjE4YTVjZDAzYWVkYzIxYWI2NmIzYzFjYzMzZWFmYmVjMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4GzvGEawC3GNY51Un_wb51LAxTHjcSol0Fw2malbClY)
> > 
> > 验证码在Yunzai的日志里 不会在gocq的日志
> > 
> > 至于你的这个问题 你的gocq连接的不是你的后端 验证码当然不会在你的后端出现 这是你的问题 和项目没有关系
> 
> 怎么就不是我的后端了。。。端口都是我自己设置的

你没有提供你后端的日志
如果第二张Yunzai日志图是你的后端
那么gocq连接的就不是你的后端

因为第二张图的日志里没有提示gocq建立连接
而且开放的地址是本机地址
如果你不会使用gocq
那么就用ICQQ-Plugin
