### ISSUE TITLE
能问下该如何关闭bot以及插件的自动更新吗？将自动更新设置为0后并不是关闭，而是以极小间隔重复更新操作

### ISSUE THREAD

**Issue by SunshineboyZj** [TimeRainStarSky/Yunzai#62]
一觉醒来号封了一天😂因为我只是借助ws-plugin来对接其它bot，云崽本身的功能并不使用
自动更新不能像下面的自动重启默认0那样关掉，设置为0后并不是关掉，只是更新间隔变得非常小😂
请问该如何关闭bot以及插件的自动更新，或者能提供途径关掉更新消息推送到主人QQ号也行😘
![Screenshot_20231212_050247](https://github.com/TimeRainStarSky/Yunzai/assets/81549837/eb3bc173-23ab-4e4b-adc9-04bc2abd28a5)

https://github.com/TimeRainStarSky/Yunzai/assets/81549837/5fa3c5c8-6a68-42a1-9976-066d99ab8741

**Comment by TimeRainStarSky** [comment]
0就是关闭，那个bug已经修复了，没更新导致的

**Comment by SunshineboyZj** [comment]
> 0就是关闭，那个bug已经修复了，没更新导致的

最新版也是v3.1.3吗（今天刚重装的）
![v3.1.3](https://github.com/TimeRainStarSky/Yunzai/assets/81549837/278fb3a6-6dfc-4ead-85d6-6652074835f3)
九天前前就已经是这个版本了（都是用的TRSS Script）
![12-03](https://github.com/TimeRainStarSky/Yunzai/assets/81549837/28b582d3-9371-4071-9133-fec2db44edcb)
晚上再看看😂
