### ISSUE TITLE
#更新面板 错误 Cannot read properties of undefined (reading '昔日宗室之仪')

### ISSUE THREAD

**Issue by Bearlele** [TimeRainStarSky/Yunzai#63]
1|TRSS-Yunzai  | [TRSSYz][11:59:17.026][MARK] 【面板】116049616 ：开始请求数据，面板服务：MiniGG-Api...
1|TRSS-Yunzai  | [TRSSYz][11:59:17.346][MARK] 【面板】116049616 ：请求结束，请求用时319ms，面板服务：MiniGG-Api...
1|TRSS-Yunzai  | NoteUser.ckUids 默认返回原神UID，可更改为 user.getCkUidList(game)
1|TRSS-Yunzai  | [TRSSYz][11:59:17.377][ERRO] [喵喵:角色面板][profileRefresh]
1|TRSS-Yunzai  | [TRSSYz][11:59:17.377][ERRO] TypeError: Cannot read properties of undefined (reading '昔日宗室之仪')
1|TRSS-Yunzai  |     at Object.check (file:///root/Yunzai/plugins/miao-plugin/resources/meta-gs/character/%E9%A6%99%E8%8F%B1/calc_auto.js:45:64)
1|TRSS-Yunzai  |     at file:///root/Yunzai/plugins/miao-plugin/models/dmg/DmgAttr.js:143:31
1|TRSS-Yunzai  |     at arrayEach (/root/Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:530:11)
1|TRSS-Yunzai  |     at Function.forEach (/root/Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:9410:14)
1|TRSS-Yunzai  |     at Object.calcAttr (file:///root/Yunzai/plugins/miao-plugin/models/dmg/DmgAttr.js:134:12)
1|TRSS-Yunzai  |     at Proxy.calcData (file:///root/Yunzai/plugins/miao-plugin/models/ProfileDmg.js:145:27)
1|TRSS-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|TRSS-Yunzai  |     at async Proxy.calcDmg (file:///root/Yunzai/plugins/miao-plugin/models/Avatar.js:348:12)
1|TRSS-Yunzai  |     at async ProfileRank.getTypeValue (file:///root/Yunzai/plugins/miao-plugin/models/ProfileRank.js:401:17)
1|TRSS-Yunzai  |     at async ProfileRank.getTypeRank (file:///root/Yunzai/plugins/miao-plugin/models/ProfileRank.js:332:15)

**Comment by TimeRainStarSky** [comment]
https://github.com/yoimiya-kokomi/miao-plugin/issues/new
