### ISSUE TITLE
是否考虑检测一些关键插件，做出一些相应提示

### ISSUE THREAD

**Issue by amumu2000** [TimeRainStarSky/Yunzai#67]
比如。检测bot存在xiaoyao-cvs-plugin，在用户无本地抽卡记录时，用户通过【#抽卡帮助】指令获取【祈愿记录统计-帮助】时，bot所发送的图片帮助，对于非专业人士，教程过于繁琐。可否通过TRSS代码方式检测是否存在某一插件，为用户增加，【检测到xiaoyao插件，用户可以发送【#扫码登录】获取用户Cookie后，直接发送【#更新抽卡记录命令】，获取抽卡记录】的友好提示。
`这个已经影响到正常使用了`
~~考虑到BOT作为上层。通过if方式判断是否存在某一插件，显然不是明智的选择。~~
~~搞个插件，命令拦截的话，又何尝不是NTR~~
~~然后改【#帮助】，他们又不看，看别人发【#角色记录】，自己也发，然后自己没记录，自己又不会搞。f**k！~~

**Comment by TimeRainStarSky** [comment]
你可以写一个这样的插件
