### ISSUE TITLE
查询米游社攻略时，puppeteer报错

### ISSUE THREAD

**Issue by gxy12345** [TimeRainStarSky/Yunzai#7]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/13727139/233587798-59a8ad3a-82af-4466-8ec2-bf38b102d6d7.png">
如图，使用 #米游社七七 这个命令可以稳定复现

**Comment by TimeRainStarSky** [comment]
上游 Miao-Yunzai 问题，已经解决
