### ISSUE TITLE
为什么使用PC微信端的时候收到的消息不会转发到ws-plugin

### ISSUE THREAD

**Issue by KeluIsAfkeru** [TimeRainStarSky/Yunzai#71]
为什么使用PC微信端的时候收到的消息不会转发到通过ws-plugin插件反向ws连接的nonebot上。

**Comment by jiangyin14** [comment]
> 为什么使用PC微信端的时候收到的消息不会转发到通过ws-plugin插件反向ws连接的nonebot上。

建议使用“WeChat-Plugin”（底层为wechat4u.js），原先的ComWechat已经是不稳定 过时的技术了

**Comment by KeluIsAfkeru** [comment]
> > 为什么使用PC微信端的时候收到的消息不会转发到通过ws-plugin插件反向ws连接的nonebot上。
> 
> 建议使用“WeChat-Plugin”（底层为wechat4u.js），原先的ComWechat已经是不稳定 过时的技术了 是并不受支持的

用了Wechat-Plugin，但是微信收到的message还是没有上报到ws-plugin反向ws的nonebot上去。

**Comment by KeluIsAfkeru** [comment]
> > 为什么使用PC微信端的时候收到的消息不会转发到通过ws-plugin插件反向ws连接的nonebot上。
> 
> 建议使用“WeChat-Plugin”（底层为wechat4u.js），原先的ComWechat已经是不稳定 过时的技术了 是并不受支持的

我傻了，排查了一圈，原来是ws-plugin上代理的uid填的不是微信的id

**Comment by jiangyin14** [comment]
> > > 为什么使用PC微信端的时候收到的消息不会转发到通过ws-plugin插件反向ws连接的nonebot上。
> 
> > 
> 
> > 建议使用“WeChat-Plugin”（底层为wechat4u.js），原先的ComWechat已经是不稳定 过时的技术了 是并不受支持的
> 
> 
> 
> 我傻了，排查了一圈，原来是ws-plugin上代理的uid填的不是微信的id

哈哈
