### ISSUE TITLE
发送#体力同时返回原神和崩铁体力是怎么实现的

### ISSUE THREAD

**Issue by Fahaxikiii** [TimeRainStarSky/Yunzai#72]
大佬们求帮忙

**Comment by AEDELSTAN** [comment]
> 大佬们求帮忙

你好，方便告知一下如何实现吗😂

**Comment by Fahaxikiii** [comment]
> > 大佬们求帮忙
> 
> 你好，方便告知一下如何实现吗😂

不会😂

**Comment by AEDELSTAN** [comment]
> > > 大佬们求帮忙
> > 
> > 你好，方便告知一下如何实现吗😂
> 
> 不会😂

好叭~
