### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'redis' imported from /root/Yunzai/lib/config/redis.js

### ISSUE THREAD

**Issue by JQ-28** [TimeRainStarSky/Yunzai#73]
<img width="631" alt="报错" src="https://github.com/TimeRainStarSky/Yunzai/assets/106399011/50a71d5d-5f49-4630-ac4d-5424a0d6c215">
<img width="594" alt="文件" src="https://github.com/TimeRainStarSky/Yunzai/assets/106399011/209197aa-1fc5-4343-a952-eb8e317eaa69">

**Comment by Yaemikoa** [comment]
I have the same problem, do you know how to solve it?

**Comment by DrSmoothl** [comment]
同样的问题，请问如何解决

**Comment by DrSmoothl** [comment]
@TimeRainStarSky

**Comment by JQ-28** [comment]
> 同样的问题，请问如何解决

我刚刚也遇到了一次，是这么解决的
一开始先试了下pnpm i发现装上了redis然后重启了一下发现有好多报错，然后后面我先把bot根目录下的node_modules删掉然后进入cmd窗口执行pnpm i就恢复了

**Comment by Yaemikoa** [comment]
> 我刚刚也遇到了一次，是这么解决的 一开始先试了下pnpm i发现装上了redis然后重启了一下发现有好多报错，然后后面我先把bot根目录下的node_modules删掉然后进入cmd窗口执行pnpm i就恢复了

多谢，我尝试了你的办法，pnpm i后重启，就恢复正常了
