### ISSUE TITLE
QQBot发送图片超时报错

### ISSUE THREAD

**Issue by KeluIsAfkeru** [TimeRainStarSky/Yunzai#75]
发送稍微大点的图片会报axios超时错误，怎么解决。
![image](https://github.com/TimeRainStarSky/Yunzai/assets/107661829/9a187d8b-36f9-496c-9d3f-ce861d88013f)

**Comment by AIxPha** [comment]
腾讯限制5秒内完成
最简单就是升级上行带宽
或者使用MD发图
有能力也可以自行对接图床
