### ISSUE TITLE
使用LLOneBot报错

### ISSUE THREAD

**Issue by Fahaxikiii** [TimeRainStarSky/Yunzai#76]
![image](https://github.com/TimeRainStarSky/Yunzai/assets/93320886/5ba2d3d5-cfcc-409a-961f-0cd98a443c1a)

**Comment by jiangyin14** [comment]
1.开启反向WebSocket支持
2.链接ws://地址:2536/go-cqhttp
3.开启 上报自身消息
其他留空不填写 直接就能用了

**Comment by TimeRainStarSky** [comment]
Redis 设置了账号密码没填写

**Comment by Fahaxikiii** [comment]
> Redis 设置了账号密码没填写

我发现了，是我傻逼了
