### ISSUE TITLE
拉取新trss,使用onebotv11连接ws报错

### ISSUE THREAD

**Issue by linya72** [TimeRainStarSky/Yunzai#80]
![image](https://github.com/TimeRainStarSky/Yunzai/assets/107689301/88992ad9-f53a-43ae-aeec-c3baf3802f2f)

**Comment by TimeRainStarSky** [comment]
连的什么

**Comment by linya72** [comment]
onebots（基于icqq的onebot管理应用）

**Comment by TimeRainStarSky** [comment]
检查有没有选错成ob12，如果没有，bot.yaml 日志改成 debug 截图

**Comment by TimeRainStarSky** [comment]
onebots兼容性有问题，找作者去
