### ISSUE TITLE
使用llonebot-docker报错

### ISSUE THREAD

**Issue by Fahaxikiii** [TimeRainStarSky/Yunzai#81]
在docker内添加反向 WebSocket地址 ws://localhost:2536/OneBotv11 后将容器端口 2536 绑定主机端口 2536 后，启动 Yunzai 报错端口 2536 已被使用
![image](https://github.com/TimeRainStarSky/Yunzai/assets/93320886/f31c6f6b-c7d4-455f-985b-531703c99775)

**Comment by TimeRainStarSky** [comment]
把 容器端口 2536 绑定主机端口 2536 是错误的
