### ISSUE TITLE
大概是新版trss的问题

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [TimeRainStarSky/Yunzai#82]
![image](https://github.com/TimeRainStarSky/Yunzai/assets/117198625/a525d3cf-8a90-4d3e-b324-cc07a86f5b2b)

**Comment by S-t-e-v-e-e** [comment]
![Screenshot_2024-03-21-22-19-04-631_mark via-edit](https://github.com/TimeRainStarSky/Yunzai/assets/117198625/a95e9b68-a7bd-4c9d-a8e1-3a45a1fb5c6f)

**Comment by TimeRainStarSky** [comment]
Node.js版本多少

**Comment by S-t-e-v-e-e** [comment]
> Node.js版本多少

![image](https://github.com/TimeRainStarSky/Yunzai/assets/117198625/b8e78b52-8d50-453e-869b-a2d9e6a75f2f)

**Comment by RinLin-NYA** [comment]
> Node.js版本多少

Node v21.4.6 实测出问题

**Comment by TimeRainStarSky** [comment]
> > Node.js版本多少
> 
> Node v21.4.6 实测出问题

找作者适配新版fetch，可先使用旧版
```
git reset --hard
git pull --rebase
pnpm up node-fetch@latest
```

**Comment by Morpheusr** [comment]
![photo_2024-05-03_14-41-10](https://github.com/TimeRainStarSky/Yunzai/assets/97303603/a9001bd7-2aad-48e9-b822-1267f672407e)
我这也是,nodejs版本22.1.0
