### ISSUE TITLE
使用PyBot插件报错

### ISSUE THREAD

**Issue by okatu-loli** [TimeRainStarSky/Yunzai#85]
![image](https://github.com/TimeRainStarSky/Yunzai/assets/53247097/8cccf4ee-6c28-4258-9f52-19349863f1b6)
![image](https://github.com/TimeRainStarSky/Yunzai/assets/53247097/c2cc99f7-86c6-459e-ad1d-df363206ed33)
每一条消息后面都会带类似这样的错误：
示例一：
![image](https://github.com/TimeRainStarSky/Yunzai/assets/53247097/8fc3c216-d1ad-4efc-9f65-dc1b56f149da)
示例二：
![image](https://github.com/TimeRainStarSky/Yunzai/assets/53247097/8bcb0cf9-1642-424c-ba25-54a0326145fd)

**Comment by TimeRainStarSky** [comment]
不支持该插件，建议直接用ws-plugin连NoneBot
