### ISSUE TITLE
请问有没有办法屏蔽星铁功能，仅使用原神功能呢

### ISSUE THREAD

**Issue by QSlotus** [TimeRainStarSky/Yunzai#86]
如题，因为我目前在使用一个纯星铁的机器人并且不准备换掉
然后trss-yunzai包含了原神和星铁的功能，这样导致在使用时会同时触发两个星铁的bot
看着有些不舒服
请问有办法屏蔽掉星铁的吗

**Comment by TimeRainStarSky** [comment]
group.yaml 禁用或直接删除插件
