### ISSUE TITLE
json数据解析失败

### ISSUE THREAD

**Issue by Viomeat** [TimeRainStarSky/Yunzai#87]
[TRSSYz][18:18:05.847][MARK] [设置主人][master] #设置主人 处理完成 2ms
[TRSSYz][18:18:05.848][WARN] 未知消息：{"status":"failed","retcode":1400,"data":nul
l,"message":"json解析失败，请检查数据格式","wording":"json解析失败，请检查数据格式"
}

**Comment by TimeRainStarSky** [comment]
更新
