### ISSUE TITLE
机器人BUG提交

### ISSUE THREAD

**Issue by 741807012** [TimeRainStarSky/Yunzai#9]
表情功能不正常可添加可查看表情列表，不能删除和关键词触发
喵喵面板的群戳一戳无用
![image](https://user-images.githubusercontent.com/90551536/233824938-cab8a6ae-987d-492c-be30-caf66ecc3347.png)
![image](https://user-images.githubusercontent.com/90551536/233825013-bf879fd3-8b1e-4414-a1c9-8ae2d3963a79.png)

**Comment by TimeRainStarSky** [comment]
已修复
