### ISSUE TITLE
从miao-yunzai迁移TRSS-yunzai时遇到的抽卡记录问题

### ISSUE THREAD

**Issue by liuzj288** [TimeRainStarSky/Yunzai#90]
从miao-yunzai迁移抽卡记录过来发现个问题，就是使用ntqq的野生bot和官方的群bot在data/gachaJson文件夹中保存不一致，怎么才能同时使用二者并让二者抽卡记录使用同一位置？
野生bot保存位置
![image](https://github.com/TimeRainStarSky/Yunzai/assets/13833404/7b1a6325-0931-4766-8602-defbdd5c1b6d)
群bot保存位置
![image](https://github.com/TimeRainStarSky/Yunzai/assets/13833404/05665883-9665-49da-b035-fba68cf0a946)

不然的话只能手动复制？

**Comment by TimeRainStarSky** [comment]
Windows
```sh
mklink 目标 源
```
Linux
```sh
ln -vsf 源 目标
```
