### ISSUE TITLE
启动trss时卡住并无法连接协议端

### ISSUE THREAD

**Issue by fishplusheep** [TimeRainStarSky/Yunzai#91]
### 系统环境
- **操作系统**：Windows 11
- **Node.js版本**：v20.12.1

### 问题
在尝试启动TRSSyunzai应用时，程序卡在了加载插件的阶段，没有成功打印出预期的日志信息`[WebSocket] 连接地址：ws://localhost:2536/[ComWeChat,GSUIDCore,OPQBot,OneBotv11,go-cqhttp]`，导致了无法成功连接到协议端，连接似乎会自动中断

#### 细节
- 启动日志停留在加载插件的步骤，无进一步进展
- 未见预期的WebSocket连接日志输出
- 尝试连接时，连接立即或短时间内断开，无法维持稳定会话

### 图片(卡住截图及尝试连接截图)
![卡在这里不动了](https://github.com/TimeRainStarSky/Yunzai/assets/129190939/a572ecb1-9c83-451d-b8e6-2a760557e51a)
![使用Lagrange.Core连接](https://github.com/TimeRainStarSky/Yunzai/assets/129190939/e17c5604-96b1-4ad8-9496-dd97f3018c3f)
---
请帮忙看看可能的问题原因，是否与Node.js版本兼容性、系统配置或是TRSSyunzai本身有关，谢谢了
已经试过重装trss
拷到别的设备上可以正常运行
重装系统或许可以解决但不是很想

**Comment by TimeRainStarSky** [comment]
检查是否有插件在启动时卡住
